server:
  port: 8002

spring:
  application:
    name: order-service
  datasource:
    driver-class-name: dm.jdbc.driver.DmDriver
    url: jdbc:dm://10.0.9.111:5236?schema=TEST&columnNameUpperCase=false&columnNameCase=lower
    username: SYSDBA
    password: SYSDBA

  cloud:
    consul:
      host: localhost
      port: 8500

      discovery:
        register: true
        prefer-ip-address: true
        ip-address: 10.0.9.111
        health-check-path: /actuator/health
        health-check-interval: 15s

    openfeign:
      client:
        config:
          user-service:
            connect-timeout: 5000
            read-timeout: 5000

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: auto
      table-format: "\"%s\""
  type-aliases-package: com.order.entity
  mapper-locations: classpath*:mapper/*.xml
